apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topology
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all:topology
roleRef:
  kind: ClusterRole
  name: topology
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
