# permissions for end users to view gpuinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpuinfo-viewer-role
rules:
- apiGroups:
  - topology.corinternal.com
  resources:
  - gpuinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.corinternal.com
  resources:
  - gpuinfoes/status
  verbs:
  - get
